# Generated by Django 4.1.7 on 2023-02-21 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoprojectapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='1995-09-29'),
            preserve_default=False,
        ),
    ]
